pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.shashank_connector
        repoName: idp-new-repo
        build: <+input>
  stages:
    - stage:
        name: build-test123456
        identifier: buildtest1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    shell: Sh
                    command: |-
                      echo "test"
                      export test
                    outputVariables:
                      - name: TEST
                        type: String
                        value: abcd
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec: {}
  identifier: autocreationtest1
  name: Shashank-creation-test
